name: 'publish'

on:
  push:
    tags:
      - v* # When a tag starting with v is pushed, trigger the workflow, e.g. v0.1.0

jobs:
  release-windows:
    name: Release Windows
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          submodules: recursive

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.38.5'
          channel: 'stable'

      - name: Install dependencies
        run: flutter pub get

      - name: Build Windows release
        run: flutter build windows --release

      - name: Package release
        run: Compress-Archive -Path build\windows\x64\runner\Release\* -DestinationPath release-windows.zip

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: release-windows.zip
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
