name: 'publish'

on:
  push:
    tags:
      - v* # When a tag starting with v is pushed, trigger the workflow, e.g. v0.1.0
  workflow_dispatch:
    inputs:
      debug:
        description: 'Run in debug mode'
        required: false
        default: 'false'

jobs:
  release-windows:
    name: Release Windows
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          submodules: recursive

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.38.5'
          channel: 'stable'

      - name: Install dependencies
        run: flutter pub get

      - name: Build Windows release
        run: flutter build windows --release

      - name: Upload artifact
        uses: actions/upload-artifact@v6
        with:
          name: tvshow-nav-windows
          path: build\windows\x64\runner\Release\
          compression-level: 0
